# Generated by Django 5.1.2 on 2024-10-27 18:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='default@slsu.com', max_length=254, verbose_name='Email')),
                ('password', models.CharField(default='', max_length=100)),
                ('year_of_study', models.CharField(default='', max_length=20)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(default='', max_length=100)),
                ('program', models.CharField(default='', max_length=100)),
                ('contact_number', models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact number must be 11 digits', regex='^\\d{11}$')])),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
